# The URL the site will be built for
base_url = "https://eduadame.netlify.app"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_rss = true
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
default_language = "pt"
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme = "hikari"
description = "Um blog para matemáticos e informáticos de plantão"
title = "Eduardo Adame"
katex = true
highlight_theme = "1337"
[extra]
# Put all your custom variables here
author = "Eduardo Adame"
author_bio = "Buscando sempre aprender, e disseminar o que aprendi. Com 17 anos, estou desde 2013 no Youtube, e sou extremamente apaixonado por matemática e informática."
twitter = "AdameS2E"
github = "adamesalles"
youtube = "EduardoAdameSalles"
instagram = "eduadame"
email = "eadamesalles@gmail.com"
whatsapp = "5524998182272&text=Ol%C3%A1%2C%20vim%20pelo%20blog.%20Gostaria%20de%20entrar%20em%20contato"
enable_mathjax = true
auto_render_katex = true