base_url = "https://waynee95.github.io/zola-theme-hikari/"
compile_sass = true
title = "Hikari"
description = "Fluid, responsive blog theme for Zola"
generate_rss = true

[extra]
author = "John Doge"
author_bio = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex, pariatur!"
twitter = "waynee955"
github = "waynee95"
instagram = false
enable_mathjax = false
